#! /usr/bin/env python
#
# Support module generated by PAGE version 4.4.5
# In conjunction with Tcl version 8.6
#    Jan 24, 2015 07:10:20 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def TODO():
    #~ print('main2_support.TODO')
    sys.stdout.flush()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


